name: Vercel Production Deployment
on:
  push:
    branches:
      - main
    paths: ["terraform/**"]

  pull_request:
    branches:
      - main
    paths: ["terraform/**"]

jobs:
  deploy:
    name: Terraform Deploy
    if: github.ref == 'refs/heads/main'
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v2

      - name: Initialise project and deploy terraform
        run: |
          cd infra/terraform
          terraform fmt
          terraform init
          terraform apply \
          -var "vercel_api_token=${{ secrets.VERCEL_API_TOKEN }}" \
          -var "backend_url=${{ secrets.VITE_BACKEND_URL }}" \
          -var "database_url=${{ secrets.DATABASE_URL }}" \
          -var "frontend_url=${{ secrets.FRONTEND_URL }}" \
          --auto-approve=true
